### ISSUE TITLE
first, firstOrNull, single, singleOrNull convenience methods for find()ing a single Element

### ISSUE THREAD

**Issue by mkienenb** [jhannes/eaxy#6]
first, firstOrNull, single, singleOrNull to deal with the four possible restrictions (accept many or not, accept no hits or not).

Convenience method for finding exactly one element by path: Finding a set of
elements, insuring that there was exactly one result, and then
grabbing the first element in the set.

```
                    ElementSet verticesSet = mesh.find("vertices");
                    if (1 != verticesSet.size()) {
                        throw new RuntimeException("Found " +
```

verticesSet.size() + " vertices sets for geometry id=" + geometry.id()
- " name=" + geometry.name());
                      }
                      Element vertices = verticesSet.first();

Outstanding question: Would you want them to be searching arbitrary depth or direct path?

**Comment by jhannes** [comment]
I've added these now. I used the names `firstOrDefault` and `singleOrDefault` instead of `...OrNull` for homogeneity with C# (!)
